enum RepositoryActionTypes {
  SEARCH_REPOSITORIES_START = 'SEARCH_REPOSITORIES_START',
  SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS',
  SEARCH_REPOSITORIES_FAILED = 'SEARCH_REPOSITORIES_FAILED',
}

export default RepositoryActionTypes;
