const repositoryTypes = {
  SEARCH_REPOSITORIES: 'SEARCH_REPOSITORIES',
  SEARCH_REPOSITORIES_SUCCESS: 'SEARCH_REPOSITORIES_SUCCESS',
  SEARCH_REPOSITORIES_FAIL: 'SEARCH_REPOSITORIES_FAIL',
};

export default repositoryTypes;
